version: '3.1'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password
    restart: 'always'